### ISSUE TITLE
RPC server unavailable

### ISSUE THREAD

**Issue by st0rmspirit** [Mr-Un1k0d3r/PoisonHandler#1]
when i use this script to excute invoke-mimikatz,it returns error "RPC server unavailable ",so what's wrong with  it 

![image](https://user-images.githubusercontent.com/13938323/72329616-0a3c5b00-36f0-11ea-9d22-0d6614fce840.png)

**Comment by Mr-Un1k0d3r** [comment]
you command is using host as the ComputerName. it is supposed to be a variable? if so there is a missing $ in front of it. I doubt that "host" resolve to anything so it can't connect to it.

The error simply tell you that it wasn't able to establish a connection
